###############################################################################
# Seed the target GitHub repo with this skeleton.
#
# Pattern matches Azure/accelerator-bootstrap-modules/alz/github: every file in
# the source tree (minus the bootstrap/ directory and ephemeral artefacts) is
# pushed to the target repo as an individual github_repository_file resource.
#
# CAUTION: Once seeded, these resources continue to MANAGE the files. If
# someone edits a file directly in the repo, the next `terraform apply` will
# revert it. Two recommended patterns:
#   1) Set copy_skeleton_files = false after the first apply, OR
#   2) Run the bootstrap once, then `terraform state rm 'github_repository_file.skeleton'`
#      so day-to-day commits become free-form.
###############################################################################

locals {
  skeleton_root = abspath("${path.module}/${var.skeleton_source_path}")

  # Top-level prefixes we never want to push (forward slashes — fileset
  # always returns POSIX-style paths even on Windows).
  skeleton_excluded_prefixes = [
    "bootstrap/",
    "powershell/",
    "starters/",
    "tests/",
    "docs/proposals/",
    ".git/",
    ".terraform/",
    ".vs/",
    ".vscode/",
    ".devcontainer/",
  ]

  # Regexes evaluated against the relative path. Anchor as needed.
  skeleton_excluded_regexes = [
    "/\\.terraform/",                  # nested terraform caches
    "(^|/)\\.terraform\\.lock",        # provider lock files
    "(^|/)terraform\\.tfstate",        # state + state.backup (with or without dir prefix)
    "(^|/)tfplan$",                    # bare plan file (no extension)
    "\\.tfplan$",                      # *.tfplan
    "(^|/)terraform\\.tfvars$",        # local tfvars at any depth — placeholders/secrets
    "(^|/)terraform\\.auto\\.tfvars$", # auto.tfvars — bootstrap renders this directly
    "(^|/)\\.env$",
    "\\.DS_Store$",
    "/\\.gitkeep$",
    "(^|/)-[a-zA-Z]$",              # stray shell-redirect artefacts like "-w"
    "(^|/)\\.run\\.log$",           # local run logs
    "^SECURITY\\.md$",              # accelerator OSS governance - not for vended repos
    "^SUPPORT\\.md$",               # accelerator OSS governance - not for vended repos
    "^docs/starter-contract\\.md$", # accelerator development contract
    "^CODEOWNERS$",                 # accelerator CODEOWNERS - vending repo gets a rendered one
  ]

  skeleton_files_all = toset(fileset(local.skeleton_root, "**/*"))

  skeleton_files = [
    for f in local.skeleton_files_all : f
    if alltrue([for p in local.skeleton_excluded_prefixes : !startswith(f, p)])
    && alltrue([for r in local.skeleton_excluded_regexes : length(regexall(r, f)) == 0])
  ]
}

resource "github_repository_file" "skeleton" {
  for_each = var.copy_skeleton_files ? toset(local.skeleton_files) : toset([])

  repository = local.github_repo_name
  branch     = var.github_default_branch
  file       = each.value
  content    = file("${local.skeleton_root}/${each.value}")

  # [skip ci] prevents the seeded files from auto-triggering apply.yml
  # before all repo Actions variables are guaranteed to exist.
  commit_message = "chore(bootstrap): seed ${each.value} [skip ci]"
  commit_author  = var.skeleton_commit_author
  commit_email   = var.skeleton_commit_email

  overwrite_on_create = true
}

###############################################################################
# Render terraform/terraform.auto.tfvars into the seeded repo so the
# workflows can `terraform plan` without operator post-processing. This file
# carries the platform-wide context (tenant/billing/MGs/hub VNet/tags) that
# is identical for every subscription vended from this repo.
###############################################################################

locals {
  auto_tfvars_content = <<-EOT
    # ---------------------------------------------------------------------------
    # Auto-loaded by Terraform when run from the `terraform/` directory.
    # Generated by the bootstrap module — do not edit by hand. Update by
    # re-running the bootstrap (or rotating these values in the bootstrap's
    # own terraform.tfvars and re-applying).
    # ---------------------------------------------------------------------------
    tenant_id               = "${var.tenant_id}"
    vending_subscription_id = "${var.platform_subscription_id}"

    billing_scopes = {
    %{~for k, v in local.resolved_billing_scopes~}
      ${k} = "${v}"
    %{~endfor~}
    }

    management_group_ids = {
    %{~for k, v in var.management_group_ids~}
      ${k} = "${v}"
    %{~endfor~}
    }

    hub_virtual_network_resource_id = ${var.hub_virtual_network_resource_id != "" ? "\"${var.hub_virtual_network_resource_id}\"" : "null"}

    # Cost-allocation tag (operator-configurable)
    cost_allocation_tag_key  = "${coalesce(var.cost_allocation_tag.name, "projectcode")}"
    cost_allocation_required = ${coalesce(var.cost_allocation_tag.required, false)}
    cost_allocation_pattern  = ${var.cost_allocation_tag.pattern == null ? "null" : "\"${var.cost_allocation_tag.pattern}\""}

    %{~if length(var.mandatory_tags) > 0~}
    mandatory_tags = {
    %{~for k, v in var.mandatory_tags~}
      "${k}" = "${v}"
    %{~endfor~}
    }
    %{~endif~}
  EOT
}

resource "github_repository_file" "platform_auto_tfvars" {
  repository = local.github_repo_name
  branch     = var.github_default_branch
  file       = "terraform/terraform.auto.tfvars"
  content    = local.auto_tfvars_content

  commit_message = "chore(bootstrap): seed terraform/terraform.auto.tfvars [skip ci]"
  commit_author  = var.skeleton_commit_author
  commit_email   = var.skeleton_commit_email

  overwrite_on_create = true
}

###############################################################################
# Render .github/CODEOWNERS from the template, using the operator's chosen
# default team plus per-archetype overrides. The verbatim copy excludes the
# bootstrap/ tree (and therefore the template) so the seeded repo only ever
# sees the rendered CODEOWNERS.
###############################################################################

locals {
  codeowners_default_team_effective = var.codeowners_default_team != "" ? var.codeowners_default_team : "@your-org/platform-team"

  codeowners_archetypes = {
    for archetype, _ in var.management_group_ids :
    archetype => distinct(concat(
      [local.codeowners_default_team_effective],
      lookup(var.codeowners_archetype_teams, archetype, [])
    ))
  }
}

resource "github_repository_file" "codeowners" {
  repository = local.github_repo_name
  branch     = var.github_default_branch
  file       = ".github/CODEOWNERS"
  content = templatefile("${path.module}/templates/CODEOWNERS.tftpl", {
    default_team     = local.codeowners_default_team_effective
    archetype_owners = local.codeowners_archetypes
  })

  commit_message = "chore(bootstrap): seed .github/CODEOWNERS [skip ci]"
  commit_author  = var.skeleton_commit_author
  commit_email   = var.skeleton_commit_email

  overwrite_on_create = true
}
